[package]
name = "libtiny_tui"
version = "0.1.0"
description = "A terminal UI for tiny"
edition = "2018"

[features]
default = []
desktop-notifications = ["notify-rust"]

[dependencies]
futures = { version = "0.3.1", default-features = false, features = ["std", "async-await"] }
libtiny_ui = { path = "../libtiny_ui" }
log = "0.4"
notify-rust = { version = "3", optional = true }
serde = { version = "1.0.8", features = ["derive"] }
serde_yaml = "0.7.1"
tempfile = "3.0.3"
term_input = { path = "../term_input" }
termbox_simple = { path = "../termbox" }
time = "0.1"
tokio = { version = "0.2.11", default-features = false, features = ["sync", "rt-core", "rt-util", "blocking", "signal", "stream", "time"] }

[dev-dependencies]
criterion = "0.3"
libc = "0.2.22"
mio = "0.6.9"

[[bench]]
name = "tui_benches"
harness = false
